name: Event Understanding Lab
on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
  pull_request:
    types: [opened, reopened]
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:
    inputs:
      reason:
        description: 'Why are you running this manually?'
        required: true
        default: 'Testing'
permissions:
  contents: write
jobs:
  detect-event:
    runs-on: ubuntu-latest
    outputs:
      version_tag: ${{ steps.generate_id.outputs.new_tag }}
    steps:
      - name: Generate unique ID
        id: generate_id 
        run: |
          TAG="v$(date +'%Y%m%d-%H%M%S')"
          echo "new_tag=$TAG" >> $GITHUB_OUTPUT
          echo "Generated Tag: $TAG"
  backend-deployment:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Push Job
        run: echo "Deploying backend from push event."
  pr-review-check:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: PR Job
        run: echo "Reviewing code from pull request."
  manual-maintenance:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Manual Job
        run: echo "Manual Job"
  create-release:
    needs: [detect-event]
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Check Received Tag
        run: echo "The tag received from detect-event is ${{ needs.detect-event.outputs.version_tag }}"
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ needs.detect-event.outputs.version_tag }}
          name: Release ${{ needs.detect-event.outputs.version_tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

